name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    container:
      image: registry.fedoraproject.org/fedora:latest

    steps:
      - run: dnf install -y rpmlint
      - uses: actions/checkout@v3
      - run: rpmlint *.spec
